### ISSUE TITLE
Feature Request: OpenAPI document driven RestAPI Design in AWS CDK for Python/Typescript/C#

### ISSUE THREAD

**Issue by aws-josterm** [aws-samples/aws-cdk-examples-proserve#2]
### General Information

An API Gateway/Lambda Rest API is created in a stack using an OpenAPI definition file to define the API methods. This will include API Gateway request validators and Integration within the definition file. It will eliminate the need to define the API methods in the stack file. Example code will be available in Typescript and Python.

### Proposed Solution

This solution provides sample code to the user that sets up a basic Lambda function, defines the OpenAPI definition file as an Asset API Definition an adds this definition to an API Gateway Instance.  

### Language

Typescript, Python, C#

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by tdcsrq** [comment]
Hi Jonathan, I think this is a great idea. I'm going to close the issue, but please move forward with the details. I'll message you directly with more details.
